server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
    username: library_admin
    password: library_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000

logging:
  level:
    com.library: DEBUG